---
- name: (RedHat 8) Install EPEL & ELRepo repository
  ansible.builtin.yum:
    name:
      - https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
      - https://www.elrepo.org/elrepo-release-8.el8.elrepo.noarch.rpm
    update_cache: "{{ wireguard_update_cache }}"

- name: (RedHat 8) Ensure WireGuard DKMS package is removed
  ansible.builtin.yum:
    name:
      - "wireguard-dkms"
    state: absent

- name: (RedHat 8) Install WireGuard packages
  ansible.builtin.yum:
    name:
      - "kmod-wireguard"
      - "wireguard-tools"
    state: present
